INSERT INTO users (name, email, password)
VALUES
('Adam Jones', 'AdamJones@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Emily Jones', 'EmilyJones@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Marshall Law', 'MarshallLaw@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Amy Law', 'AmyLaw@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
('Catarina Hess', 'CatarinaHess@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.')

INSERT INTO properties (title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code)
VALUES 
('Magic ar', 'fill stick belong fly construction wave positive mean gently happy alone event thousand wore sick rope fighting typical popular nuts built swept particular eye salmon rate explain follow adventure outline dish library heart strength selection pocket teeth production bread everybody luck stage hundred atomic forgotten drove am found forget similar social thousand mass breathe border touch box suit pull into receive felt higher flat question tip slide nearly since branch society herd hurt without ever zoo stuck laugh tomorrow own fall position judge structure new danger mean pig lower steel have weak great either make body long hurry vegetable kept together east straw muscle get broad torn rocket total tribe waste thus careful sentence camera lonely horse doctor spite deeply sudden using rising bag graph pond pine bicycle likely studied rocky near twelve return again film pan dull offer roll effect bone customs wonderful rain gas sets organization bowl coat decide wild remarkable paragraph another check question afternoon helpful climate news bring instrument dozen wing yes aloud stone red eight image door thick us suit particles fall purpose everything perhaps wood basis root difficulty managed safe high dry equal height mainly plain lead grandfather numeral egg attached pleasure shallow did pot closely person right mathematics law tears grandfather driving species forest speech between studying fix twenty lovely brush transportation pink raise coast is grandfather throw exchange fur likely practical apartment massage highest interior slept view vowel weak cave information dug count who political band held top grandmother cause were whenever fed unit expect aid earlier neighborhood series does been certainly simply example cloth thus reach next know right anywhere partly to principle your effect get rhyme minute warn cold finger read dig sweet pride split soon dot hungry taste everything swam crack difficulty closer trunk spend hill consider mother', 128, 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg', 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg?auto=compress&cs=tinysrgb&h=350', 36317, 1, 3, 0, true, 'Quebec', 'Chicoutimi', 'Canada', '1950 Zujcol Path', '19755');    
('Magic fam', 'Comfortable stick belong fly construction wave positive mean gently happy alone event thousand wore sick rope fighting typical popular nuts built swept particular eye salmon rate explain follow adventure outline dish library heart strength selection pocket teeth production bread everybody luck stage hundred atomic forgotten drove am found forget similar social thousand mass breathe border touch box suit pull into receive felt higher flat question tip slide nearly since branch society herd hurt without ever zoo stuck laugh tomorrow own fall position judge structure new danger mean pig lower steel have weak great either make body long hurry vegetable kept together east straw muscle get broad torn rocket total tribe waste thus careful sentence camera lonely horse doctor spite deeply sudden using rising bag graph pond pine bicycle likely studied rocky near twelve return again film pan dull offer roll effect bone customs wonderful rain gas sets organization bowl coat decide wild remarkable paragraph another check question afternoon helpful climate news bring instrument dozen wing yes aloud stone red eight image door thick us suit particles fall purpose everything perhaps wood basis root difficulty managed safe high dry equal height mainly plain lead grandfather numeral egg attached pleasure shallow did pot closely person right mathematics law tears grandfather driving species forest speech between studying fix twenty lovely brush transportation pink raise coast is grandfather throw exchange fur likely practical apartment massage highest interior slept view vowel weak cave information dug count who political band held top grandmother cause were whenever fed unit expect aid earlier neighborhood series does been certainly simply example cloth thus reach next know right anywhere partly to principle your effect get rhyme minute warn cold finger read dig sweet pride split soon dot hungry taste everything swam crack difficulty closer trunk spend hill consider mother', 128, 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg', 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg?auto=compress&cs=tinysrgb&h=350', 36317, 1, 3, 0, true, 'Quebec', 'Chicoutimi', 'Canada', '1950 Zujcol Path', '19755');    
('Magic ili', 'Comfortable fill belong fly construction wave positive mean gently happy alone event thousand wore sick rope fighting typical popular nuts built swept particular eye salmon rate explain follow adventure outline dish library heart strength selection pocket teeth production bread everybody luck stage hundred atomic forgotten drove am found forget similar social thousand mass breathe border touch box suit pull into receive felt higher flat question tip slide nearly since branch society herd hurt without ever zoo stuck laugh tomorrow own fall position judge structure new danger mean pig lower steel have weak great either make body long hurry vegetable kept together east straw muscle get broad torn rocket total tribe waste thus careful sentence camera lonely horse doctor spite deeply sudden using rising bag graph pond pine bicycle likely studied rocky near twelve return again film pan dull offer roll effect bone customs wonderful rain gas sets organization bowl coat decide wild remarkable paragraph another check question afternoon helpful climate news bring instrument dozen wing yes aloud stone red eight image door thick us suit particles fall purpose everything perhaps wood basis root difficulty managed safe high dry equal height mainly plain lead grandfather numeral egg attached pleasure shallow did pot closely person right mathematics law tears grandfather driving species forest speech between studying fix twenty lovely brush transportation pink raise coast is grandfather throw exchange fur likely practical apartment massage highest interior slept view vowel weak cave information dug count who political band held top grandmother cause were whenever fed unit expect aid earlier neighborhood series does been certainly simply example cloth thus reach next know right anywhere partly to principle your effect get rhyme minute warn cold finger read dig sweet pride split soon dot hungry taste everything swam crack difficulty closer trunk spend hill consider mother', 128, 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg', 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg?auto=compress&cs=tinysrgb&h=350', 36317, 1, 3, 0, true, 'Quebec', 'Chicoutimi', 'Canada', '1950 Zujcol Path', '19755');    

INSERT INTO reservations (guest_id, property_id, start_date, end_date) 
VALUES (1, 1, '2018-09-11', '2018-09-26'),
(2, 2, '2019-01-04', '2019-02-01'),
(3, 3, '2021-10-01', '2021-10-14');

INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) 
VALUES (891, 477, 1013419, 4, 'Ceh befboh ara jezubu nemicig guco rubanbo ebsu ij pita cilene mi.');
VALUES (977, 635, 1011306, 4, 'Zojicvi jej mouruvu wugola dupwi ofawig hifvocra bulnivucu use mu wanecsus pofmagviv.');
VALUES (97, 625, 1011906, 1, 'Zojicvi jej mouruvu wugola dupwi ofawig hifvocra bulnivucu use mu wanecsus pofmagviv.');